name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate Shell Script
        run: bash -n samplecode.sh

      - name: Lint Check
        run: echo "Lint successful"

      - name: Build Preview
        run: echo "Build successful"

      - name: Deploy
        run: echo "Deployment successful"
